// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Projeto Supabase oficial (com os dados reais do site).
// A chave publicável é segura para uso no cliente: o acesso é protegido por RLS.
// Pode ser sobrescrita via variaveis de ambiente VITE_SUPABASE_* se necessario.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://htqxxfgvhowdepzccbqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_qkRyq-d_VHfo1eMsGEOelA_TYjKK15w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
